/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erhannis.connections;

import com.erhannis.connections.vjcsp.VJCSPNetwork;
import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;

/**
 *
 * @author erhannis
 */
public class ConnectionsPanel extends javax.swing.JPanel {

  //TODO This doesn't seem very generic
  protected VJCSPNetwork network;
  
  /**
   * Creates new form ConnectionsPanel
   */
  public ConnectionsPanel() {
    initComponents();
  }
  
  public void setNetwork(VJCSPNetwork network) {
    this.network = network;
    this.repaint();
  }
  
  public VJCSPNetwork getNetwork() {
    return network;
  }

  @Override
  protected void paintComponent(Graphics g0) {
    super.paintComponent(g0); //To change body of generated methods, choose Tools | Templates.
    Graphics2D g = (Graphics2D)g0;

    AffineTransform saveAT = g.getTransform();

    g.setTransform(new AffineTransform(10, 0, 0, 10, 200, 200));
    //g.transform(t);
      g.setStroke(new BasicStroke(0));
    
    // Do stuff
    if (network != null) {
      network.draw(g);
    }
    
    g.setTransform(saveAT);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
